import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-specialty-pharmacy-manufacturer-rebate-recovery",
  "engine": "recovery",
  "title": "Specialty Pharmacy Manufacturer Rebate Recovery",
  "shortTitle": "Specialty Pharmacy Manufacturer Rebate Recovery",
  "tagline": "Capture manufacturer rebates and service fees earned through specialty-drug volume, outcomes, and contracted data delivery.",
  "industry": "Specialty Pharmacy Finance",
  "buyer": "Specialty pharmacies and health systems",
  "uiPort": 4647,
  "apiPort": 5647,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Specialty Pharmacy Manufacturer Rebate Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments in one accountable workflow. Capture manufacturer rebates and service fees earned through specialty-drug volume, outcomes, and contracted data delivery.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Specialty Pharmacy Manufacturer Rebate Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("manufacturer-agreement-library","SPM01","Manufacturer agreement library","Execute manufacturer agreement library using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed manufacturer agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Manufacturer agreement library Reference","text","SPM01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("ndc-product-registry","SPM02","NDC product registry","Execute ndc product registry using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed ndc product registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","NDC product registry Reference","text","SPM02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("eligible-dispense-ingestion","SPM03","Eligible dispense ingestion","Execute eligible dispense ingestion using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed eligible dispense ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Eligible dispense ingestion Reference","text","SPM03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("patient-program-qualification","SPM04","Patient program qualification","Execute patient program qualification using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed patient program qualification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Patient program qualification Reference","text","SPM04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("volume-tier-calculation","SPM05","Volume tier calculation","Execute volume tier calculation using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Volume tier calculation Reference","text","SPM05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("market-share-calculation","SPM06","Market-share calculation","Execute market-share calculation using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed market-share calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Market-share calculation Reference","text","SPM06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("adherence-measure-validation","SPM07","Adherence measure validation","Execute adherence measure validation using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed adherence measure validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Adherence measure validation Reference","text","SPM07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("outcome-guarantee-evidence","SPM08","Outcome guarantee evidence","Execute outcome guarantee evidence using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed outcome guarantee evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Outcome guarantee evidence Reference","text","SPM08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("data-submission-sla","SPM09","Data submission SLA","Execute data submission sla using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed data submission sla decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Data submission SLA Reference","text","SPM09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("invoice-generation","SPM10","Invoice generation","Execute invoice generation using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed invoice generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Invoice generation Reference","text","SPM10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("manufacturer-deduction-review","SPM11","Manufacturer deduction review","Execute manufacturer deduction review using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed manufacturer deduction review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Manufacturer deduction review Reference","text","SPM11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("credit-memo-reconciliation","SPM12","Credit memo reconciliation","Execute credit memo reconciliation using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed credit memo reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Credit memo reconciliation Reference","text","SPM12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("dispute-package","SPM13","Dispute package","Execute dispute package using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Dispute package Reference","text","SPM13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("cash-collection-tracking","SPM14","Cash collection tracking","Execute cash collection tracking using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed cash collection tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Cash collection tracking Reference","text","SPM14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]}),
feature("program-drug-economics","SPM15","Program drug economics","Execute program drug economics using manufacturer agreements, NDCs, dispenses, patient eligibility, adherence measures, data submissions, tier guarantees, invoices, credits, and payments.","Produce a governed program drug economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Manufacturer / Drug Program","text","Manufacturer / Drug Program · Standard Case"],["caseReference","Program drug economics Reference","text","SPM15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",562500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",680625],["domainDriver","Rebate Program","select","Volume",["Volume","Adherence","Data service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Manufacturer agreement library case","NDC product registry case","Eligible dispense ingestion case","Patient program qualification case","Volume tier calculation case"]})
]);
